net5 compilation and delete obsolete code
DataObjects-NET/dataobjects-net pull request #179
Opened 2021-10-21 19:47 UTC by SergeiPavlov

This copy of @AlexUstinov 's PR into http://github.com/servicetitan/dataobjects-net

2021-11-17 13:29 UTC, alex-kulakov requested changes
Please take a look at the comments.
Also I don't agree with ```PostgresqlSqlDml``` rename. The class supposes to contain an extended operations for, in this case, PostgreSQL. Its name is similar to general ```SqlDml``` static class which contains variety of different methods that help building ```SqlExpression```s.  Thought ```PostgresqlSqlDml``` contains only geometric functions it can be extended with more functions. Same thing for ```PostgresqlSqlFunctionType``` rename.

About local functions usage. I noticed several of them that I wanted to change. e.g. in ```Node.cs``` and ```DelegateHelper```. Local functions are faster than Func/Action so I'm all for it. They also can be placed anywhere within parent method as oppose to delegates. So why not to improve code reading experience by moving them, for example, to the end like it is shown in examples [here](https://docs.microsoft.com/ru-ru/dotnet/csharp/programming-guide/classes-and-structs/local-functions)? They are not always should be read, especially when their name is clear and reflects what they do. But having them in the middle of the parent methods body forces reader to find where certain function ends to continue reading main method. What's your arguments for having local functions in the middle of the parent method?

2021-11-17 22:48 UTC, SergeiPavlov commented on Orm/Xtensive.Orm/Sql/Model/PairedNodeCollection.cs
> +    }
The check is performed in `Add()` method.
I don't think this method is supposed to be atomic

2021-11-17 22:50 UTC, SergeiPavlov commented on Orm/Xtensive.Orm/Orm/Building/Builders/PartialIndexFilterBuilder.cs
> +      var fieldName = nameBuilder.ToString();
Reverse().Join()  makes more allocations for iterators

2021-11-17 22:51 UTC, SergeiPavlov commented on Orm/Xtensive.Orm/Modelling/Node.cs
> +    private static ConcurrentDictionary<Type, Lazy<PropertyAccessorDictionary>> cachedPropertyAccessors =
fixed

2021-11-17 22:51 UTC, SergeiPavlov commented on Orm/Xtensive.Orm.Tests/Upgrade/UpgradeAndNamingRulesAdvanced/TargetModels.cs
> +
fixed

2021-11-17 22:53 UTC, SergeiPavlov commented on Orm/Xtensive.Orm/Comparison/AdvancedComparer.cs
> +      new Lazy<AdvancedComparer<T>>(() => ComparerProvider.System.GetComparer<T>());
fixed name violation

2021-11-17 22:58 UTC, SergeiPavlov commented on Orm/Xtensive.Orm/Comparison/AdvancedComparer.cs
> +      new Lazy<AdvancedComparer<T>>(() => ComparerProvider.Default.GetComparer<T>());
Fixed

2021-11-17 23:05 UTC, SergeiPavlov commented on Orm/Xtensive.Orm/Orm/Rse/ColumnGroupCollection.cs
> +    public IEnumerator<ColumnGroup> GetEnumerator() => items.GetEnumerator();
fixed

2021-11-17 23:10 UTC, SergeiPavlov commented on Orm/Xtensive.Orm/Orm/Building/PrefetchActionContainer.cs
> +    private ReadOnlyCollection<PrefetchFieldDescriptor> fields;
correct, fixed

2021-11-17 23:12 UTC, SergeiPavlov commented on Orm/Xtensive.Orm/Orm/Building/PrefetchActionContainer.cs
> +          .ToList()
Used `.SelectToList()`

2021-11-17 23:16 UTC, SergeiPavlov commented on Orm/Xtensive.Orm/Orm/Building/Builders/ModelBuilder.cs
> +    private static ConcurrentDictionary<TypeKey, Lazy<Type>> generatedTypes = new ConcurrentDictionary<TypeKey, Lazy<Type>>();
done. Also converted nested function `AuxiliaryTypeFactory` into static field

2021-11-17 23:20 UTC, SergeiPavlov commented on Orm/Xtensive.Orm/Sql/ValueTypeMapping/TypeMapper.cs
> +      // we don't need to provide a functionality reading those data as byte arrays
In my view names `SqlGeometry`, `SqlGeography` are general enough.
SQL server API users know them. But for others they have no relation to Microsoft

2021-11-18 05:46 UTC, alex-kulakov commented on Orm/Xtensive.Orm/Sql/Model/PairedNodeCollection.cs
> +    }
In the base type thought the check exists in both ```AddRange``` and ```Add```. Here, ```AddRange``` is made to ignore the check. This is weird to me, so I asked why it differs

2021-11-18 06:05 UTC, alex-kulakov commented on Orm/Xtensive.Orm/Sql/ValueTypeMapping/TypeMapper.cs
> +      // we don't need to provide a functionality reading those data as byte arrays
No, they are from a Microsoft's assembly for MS Sql Server. In DO 5 these types were available to use in Entities, of course with MS Sql Server only. Other providers didn't have such types to use in Entities.

2021-11-18 06:45 UTC, SergeiPavlov commented on Orm/Xtensive.Orm/Sql/Model/PairedNodeCollection.cs
> +    }
I see the method `.AddRange()` was added looking at method `override Add()` (which is without locking check).
I agree, explicit check would be more consistent. Added it

2021-11-30 05:09 UTC, AlexUstinov commented
> Please take a look at the comments. Also I don't agree with `PostgresqlSqlDml` rename. The class supposes to contain an extended operations for, in this case, PostgreSQL. Its name is similar to general `SqlDml` static class which contains variety of different methods that help building `SqlExpression`s. Thought `PostgresqlSqlDml` contains only geometric functions it can be extended with more functions. Same thing for `PostgresqlSqlFunctionType` rename.

I'm sorry, but I didn't notice the similarity with the `SqlDml` class, but the new name is still similar though. The intention was to provide a meaningful comment to the class and I tried to identify what it actually does. Honestly, we can afford having a dedicated container type for any target DML subdomain like geometry in that case. But I don't mind renaming it back, please just suggest a proper XML comment for the type.

2021-11-30 06:07 UTC, alex-kulakov commented
For PostgresqlSqlFunctionType I would suggest 
```csharp
  /// <summary>
  /// Contains additional provider-specific SQL functions.
  /// These functions are not presented in general set of supported SQL
  /// functions and are used only within provider, e.g for operations on
  /// provider-specific types.
  /// </summary>
  public static class PostgresqlSqlFunctionType
```

```PostgresqlSqlDml``` had summary, probably it could be better, maybe like that
```csharp
  /// <summary>
  /// A factory for SQL DML operations for Postgresql DBMS.
  /// Similarly to <see cref="Xtensive.Sql.SqlDml"/> it contains
  /// factory methods for provider-specific <see cref="SqlExpression"/>s.
  /// </summary>
  public static class PostgresqlSqlFunctionType
```

Another type that lacks XML is ```SqlCustomFunctionType```. I suggest following description
```csharp
/// <summary>
  /// Defines custom function type.
  /// Used to define functions that are ouside of standard SQL functions
  /// supported by majority of providers. Such functions should be
  /// handleded by the provider within which they are declared.
  /// </summary>
  [Serializable]
  public sealed class SqlCustomFunctionType : IEquatable<SqlCustomFunctionType>

2021-11-30 06:37 UTC, SergeiPavlov commented
Renamed the classes back and changed the XML comment as suggested

2021-12-03 06:25 UTC, alex-kulakov approved these changes

2021-12-03 06:26 UTC, merged

2021-12-03 11:31 UTC, alex-kulakov commented
@AlexUstinov and @SergeiPavlov Tests are failing with NRE with stacks similar to this
```
KeyFactory.CreateGenericKey(Domain domain, String nodeId, TypeInfo type, TypeReferenceAccuracy accuracy, Tuple tuple, Int32[] keyIndexes) line 150
KeyFactory.Materialize(Domain domain, String nodeId, TypeInfo type, Tuple value, TypeReferenceAccuracy accuracy, Boolean canCache, Int32[] keyIndexes) line 60
ItemMaterializationContext.Materialize(Int32 entityIndex, Int32 typeIdIndex, TypeInfo type, Pair`1[] entityColumns, Tuple tuple) line 51
lambda_method100(Closure , Object[] , Tuple , ItemMaterializationContext )
<>c__DisplayClass2_0`4.<Bind>b__0(T2 arg2, T3 arg3) line 37
ItemMaterializer`1.Materialize(Tuple tuple, MaterializationContext context, ParameterContext parameterContext) line 24
MaterializingReader`1.get_Current() line 46
Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
Enumerable.First[TSource](IEnumerable`1 source)
QueryResultExtensions.ToScalar[TResult](QueryResult`1& sequence, ResultAccessMethod resultAccessMethod) line 15
TranslatedQuery.ExecuteScalar[TResult](Session session, ParameterContext parameterContext) line 60
QueryProvider.<ExecuteScalar>g__ExecuteScalarQuery|7_0[TResult](TranslatedQuery query, Session session, ParameterContext parameterContext) line 78
QueryProvider.Execute[TResult](Expression expression, Func`4 runQuery) line 107
QueryProvider.ExecuteScalar[TResult](Expression expression) line 81
QueryProvider.Execute[TResult](Expression expression) line 72
Queryable.First[TSource](IQueryable`1 source)
InterfaceTest.MainTest() line 134
```
Didn't tested the changes? And I missed this too so master is broken

2021-12-03 11:35 UTC, alex-kulakov commented
I'm reverting merge.

2021-12-03 21:03 UTC, SergeiPavlov commented
> I'm reverting merge.

The NRE is fixed