Memoize MakeGenericMethod(), MakeGenericType() methods (#50)
DataObjects-NET/dataobjects-net pull request #190
Opened 2021-11-11 06:18 UTC by SergeiPavlov

2021-11-22 11:25 UTC, alex-kulakov requested changes

2021-11-22 11:29 UTC, SergeiPavlov commented on Orm/Xtensive.Orm/Orm/Building/Builders/ModelBuilder.cs
> +      };
Moved it to static readonly as most optimal way

2021-11-22 11:31 UTC, SergeiPavlov commented on Orm/Xtensive.Orm/Sql/SqlDml.cs
> +      sqlLiteralType = typeof(SqlLiteral<>);
done
Actually it is called `PascalCase`
`sqlArrayType` was in `camelCase`

2021-11-22 11:35 UTC, alex-kulakov submitted a review, later dismissed

2021-11-22 14:28 UTC, SergeiPavlov commented on Orm/Xtensive.Orm/Orm/Building/Builders/AutoGenericCombinator.cs
> +using System;
I'm sure it  was done automatically by Editor.

2021-11-24 00:52 UTC, SergeiPavlov commented on Orm/Xtensive.Orm/Orm/Building/Builders/AutoGenericCombinator.cs
> +using System;
reverted it

2021-11-24 04:22 UTC, alex-kulakov commented on Orm/Xtensive.Orm/Sql/SqlDml.cs
> +      sqlLiteralType = typeof(SqlLiteral<>);
Yep, I mismatch them, but you get it right, thank you

2021-11-24 04:27 UTC, alex-kulakov approved these changes

2021-11-24 04:27 UTC, merged