Optimize SqlFunctionCall/SqlCustomFunctionCall
DataObjects-NET/dataobjects-net pull request #245
Opened 2022-04-29 07:11 UTC by SergeiPavlov

* Make abstract class `SqlFunctionCallBase` with functionality common for both `SqlFunctionCall` & `SqlCustomFunctionCall`
* Change type of  `SqlFunctionCall.Arguments` to `IReadOnlyList` to avoid unnecessary allocations
* Replace `Collection<SqlExpression>` to `List<SqlExpression>`.  List is more lightweight with same functionality
* Make `ArgumentValidator.EnsureArgumentIs<T>()` to return `T` to avoid double type casting after call
* Make EnsureArgumentIs's parameter `parameterName` automatic by using `[CallerArgumentExpression]` attribute

2022-07-19 10:59 UTC, alex-kulakov requested changes

2022-07-19 11:01 UTC, alex-kulakov commented
Also worth mentioning that FunctionCalls lost ability to change parameters after creation.

2022-07-19 21:17 UTC, SergeiPavlov commented on Orm/Xtensive.Orm/Sql/Dml/Expressions/SqlNextValue.cs
> +      SqlNextValue replacingExpression = ArgumentValidator.EnsureArgumentIs<SqlNextValue>(expression);
done

2022-07-19 21:18 UTC, SergeiPavlov commented on Orm/Xtensive.Orm/Sql/Dml/Expressions/SqlUserColumn.cs
> +      SqlUserColumn replacingExpression = ArgumentValidator.EnsureArgumentIs<SqlUserColumn>(expression);
done

2022-07-19 21:20 UTC, SergeiPavlov commented on Orm/Xtensive.Orm/Sql/Dml/Expressions/SqlNull.cs
> +      ArgumentValidator.EnsureArgumentIs<SqlNull>(expression);
sure, done

2022-07-19 22:21 UTC, SergeiPavlov commented on Orm/Xtensive.Orm/Core/ArgumentValidator.cs
> +    public static T EnsureArgumentIs<T>(object value,
added the XML doc line

2022-07-19 22:22 UTC, SergeiPavlov commented on Orm/Xtensive.Orm/Sql/Dml/Expressions/SqlVariable.cs
> +      SqlVariable replacingExpression = ArgumentValidator.EnsureArgumentIs<SqlVariable>(expression);
done

2022-07-19 22:25 UTC, SergeiPavlov commented on Orm/Xtensive.Orm/Sql/SqlDml.cs
> +      return FunctionCall(name, System.Array.Empty<SqlExpression>());
done

2022-07-19 22:29 UTC, SergeiPavlov commented
> Also worth mentioning that FunctionCalls lost ability to change parameters after creation.

I mentioned  in the PR description that `Arguments` is now immutable.

2022-07-21 11:00 UTC, alex-kulakov commented
Yes, you did, pardon me for inattention.

2022-07-22 09:37 UTC, alex-kulakov approved these changes

2022-07-22 09:39 UTC, merged