Intern short (1..2 chars) contents of TextNode
DataObjects-NET/dataobjects-net pull request #301
Opened 2023-01-11 11:11 UTC by SergeiPavlov

Most typical TextNode is  `comma+space`
Cached queries may contain Megabytes of them:
![image](https://user-images.githubusercontent.com/1176609/211781775-36fc5964-3467-4386-886d-c8cdb576817d.png)

2023-08-02 06:33 UTC, alex-kulakov commented
I'm going to change target branch to the 7.1 one, it's the version where reworked ContainerNode was introduced sounds reasonable to improve it there

2023-08-03 07:35 UTC, alex-kulakov requested changes
Static TextNode.Create(string ) methods, as all static methods should be before any instance methods.
So the order should be 
1) public readonly string Test;
2) public static TextNode Create(string text) ...
3) internal override void AcceptVisitor(NodeVisitor vistor)

2023-08-03 07:42 UTC, SergeiPavlov commented
> Static TextNode.Create(string ) methods, as all static methods should be before any instance methods.

done

2023-08-03 09:43 UTC, alex-kulakov approved these changes

2023-08-03 15:12 UTC, merged