Apply .NET8 `MethodInvoker`/`ConstructorInvoker` optimization
DataObjects-NET/dataobjects-net pull request #359
Opened 2023-11-29 15:08 UTC by SergeiPavlov

Described here:
https://github.com/dotnet/runtime/pull/88415
https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-8#reflection

2023-12-20 08:09 UTC, alex-kulakov requested changes

2023-12-20 22:01 UTC, SergeiPavlov commented on Orm/Xtensive.Orm/IoC/ServiceContainer.cs
> +      return cInfo.Invoke(new Span<object>(args));
done

2023-12-20 22:01 UTC, SergeiPavlov commented on Orm/Xtensive.Orm/Reflection/TypeHelper.cs
> +    private static readonly ConcurrentDictionary<(Type, Type[]), ConstructorInvoker> ConstructorInfoByTypes =
done

2023-12-20 22:01 UTC, SergeiPavlov commented on Orm/Xtensive.Orm/Reflection/TypeHelper.cs
> +
removed it

2023-12-20 22:01 UTC, SergeiPavlov commented on Orm/Xtensive.Orm/Reflection/TypeHelper.cs
> +      CachedMakeGenericMethod(genericDefinition, typeArgument1, typeArgument2);
done

2023-12-21 10:24 UTC, alex-kulakov approved these changes

2023-12-21 10:25 UTC, merged

2023-12-21 10:34 UTC, alex-kulakov commented
@SergeiPavlov, I'm going to make new ```GetSingleConstructorInvokerOrDefault```/```GetSingleConstructorInvoker``` methods internal. Are you ok with that?

2023-12-22 01:17 UTC, SergeiPavlov commented
I'm Ok, but what about `GetSingleConstructorOrDefault()` ? 
It is public but conditionally available only on <`.NET8`

2023-12-22 06:01 UTC, alex-kulakov commented
Well, it is public and correct way of getting it out of public is to make it obsolete and then make it internal. It is a single-usage method. Probably, it will be deleted after NET6 and NET7 will be removed from project target frameworks. For now, all I can do is to make it obsolete to hint the future for possible users.

BTW, I'll make it exist in NET8 too to prevent possible compilation error on user side on framework upgrade, another reason is that ConstructorInvoker and ConstructorInfo are not interchangeable.